Productions

diff --git a/.github/workflows/deploy-banckend.yaml b/.github/workflows/deploy-banckend.yaml
--- a/.github/workflows/deploy-banckend.yaml
+++ b/.github/workflows/deploy-banckend.yaml
@@ -3,7 +3,7 @@ name: Deploy to EC2
 on:
   push:
     branches:
-      - mains
+      - test_not_working
 
 jobs:
   deploy:
@@ -38,16 +38,23 @@ jobs:
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: af-south-1
 
-    # Step 5: Deploy to EC2 using SSH
     - name: Deploy to EC2
-      uses: appleboy/ssh-action@v0.1.5
+      uses: appleboy/ssh-action@v0.1.6
       with:
-        host: "13.244.159.92"  # Public IP of the EC2 instance
-        username: "ubuntu"  # Update if using a different username
+        host: "13.247.80.4"  # IP de l'instance EC2
+        username: "ubuntu"  # Assurez-vous que c'est l'utilisateur correct
         key: ${{ secrets.EC2_SSH_KEY }}
         port: 22
         script: |
           docker pull geraldrandriamanantena/e-learning-backend:latest
-          docker stop backend || true
-          docker rm backend || true
-          docker run -d --name backend -p 80:80 geraldrandriamanantena/e-learning-backend:latest
+          docker run -d --name backend_new -p 80:80 geraldrandriamanantena/e-learning-backend:latest
+          sleep 10
+          if [ "$(docker inspect -f '{{.State.Running}}' backend_new)" = "true" ]; then
+            docker stop backend || true
+            docker rm backend || true
+            
+            docker rename backend_new backend
+          else
+            echo "Deployment failed. New container did not start properly."
+            exit 1
+          fi
