This should work now

diff --git a/.github/workflows/deploy-banckend.yaml b/.github/workflows/deploy-banckend.yaml
--- a/.github/workflows/deploy-banckend.yaml
+++ b/.github/workflows/deploy-banckend.yaml
@@ -48,6 +48,14 @@ jobs:
         port: 22
         script: |
           docker pull geraldrandriamanantena/e-learning-backend:latest
-          docker stop backend || true
-          docker rm backend || true
-          docker run -d --name backend -p 80:80 geraldrandriamanantena/e-learning-backend:latest
+          docker run -d --name backend_new -p 80:80 geraldrandriamanantena/e-learning-backend:latest
+          sleep 10
+          if [ "$(docker inspect -f '{{.State.Running}}' backend_new)" = "true" ]; then
+            docker stop backend || true
+            docker rm backend || true
+            
+            docker rename backend_new backend
+          else
+            echo "Deployment failed. New container did not start properly."
+            exit 1
+          fi
